"""Add rejected_by_role to McpToolCall

Revision ID: da9656d7c64b
Revises: 3221165e2f5d
Create Date: 2026-07-08 11:47:02.400810+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9656d7c64b'
down_revision: Union[str, None] = '3221165e2f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_tool_calls', sa.Column('rejected_by_role', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_tool_calls', 'rejected_by_role')
    # ### end Alembic commands ###
