"""Add effective_from and effective_to to documents

Revision ID: ede34718e0cf
Revises: da9656d7c64b
Create Date: 2026-07-09 12:16:40.182430+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede34718e0cf'
down_revision: Union[str, None] = 'da9656d7c64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('effective_from', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('effective_to', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'effective_to')
    op.drop_column('documents', 'effective_from')
    # ### end Alembic commands ###
