"""Add deleted_at to sessions

Revision ID: 3221165e2f5d
Revises: 082e5dd85fd3
Create Date: 2026-07-08 10:43:22.998467+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3221165e2f5d'
down_revision: Union[str, None] = '082e5dd85fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'deleted_at')
    # ### end Alembic commands ###
