from typing import Protocol, Optional, Any, AsyncGenerator

class DataGateway(Protocol):
    # ── User Operations ──
    async def get_user_by_id(self, user_id: str) -> Optional[Any]: ...
    async def get_user_by_email(self, email: str) -> Optional[Any]: ...
    async def create_user(self, user_data: dict) -> Any: ...
    async def get_all_users(self, limit: int = 50, offset: int = 0) -> list[Any]: ...
    
    async def get_user_context_profile(self, user_id: str) -> dict: ...
    async def update_user_context_profile(self, user_id: str, data: dict) -> dict: ...

    # ── Session & Message Operations ──
    async def create_session(self, session_id: str, user_id: str, title: str) -> None: ...
    async def get_sessions_for_user(self, user_id: str) -> list[dict]: ...
    async def get_session(self, session_id: str) -> Optional[dict]: ...
    async def update_session_title(self, session_id: str, title: str) -> None: ...
    async def delete_session(self, session_id: str) -> None: ...
    
    async def save_message(self, session_id: str, role: str, content: str) -> None: ...
    async def get_session_history(self, session_id: str) -> list[dict]: ...
    async def update_message_citations(self, session_id: str, response_text: str, unverified: list[str]) -> None: ...

    # ── Pipeline & Admin Operations ──
    async def create_run(self, session_id: str, user_message: str) -> str: ...
    async def update_run(self, run_id: str, **kwargs) -> None: ...
    async def create_step(self, run_id: str, step_name: str, step_order: int) -> int: ...
    async def update_step(self, step_id: int, **kwargs) -> None: ...
    async def log_generated_file(self, file_data: dict) -> str: ...
    async def get_generated_file(self, file_id: str) -> Optional[dict]: ...
    
    async def log_mcp_tool_call(self, run_id: str, mcp_server: str, tool_name: str, status: str, input_params: dict = None, output_summary: dict = None, duration_ms: int = None, rejected_by_role: bool = False) -> None: ...
    async def log_document(self, doc_id: str, filename: str, doc_type: str = None, chunk_count: int = None, is_global: bool = False) -> None: ...
    
    async def log_generated_file(self, file_data: dict) -> None: ...
    
    async def get_system_metrics(self) -> dict: ...
    async def get_runs(self, limit: int = 50, offset: int = 0, route_filter: str = None) -> list[dict]: ...
    async def get_run_steps(self, run_id: str) -> list[dict]: ...
    async def get_generated_files(self, limit: int = 50, offset: int = 0) -> list[dict]: ...
    async def delete_generated_file(self, file_id: str) -> Optional[dict]: ...
    async def get_mcp_calls(self, limit: int = 50, offset: int = 0) -> list[dict]: ...
    
    async def get_ingested_files_summary(self) -> list[dict]: ...
    async def delete_ingested_file(self, doc_id: str) -> None: ...

    # ── Project Operations ──
    async def get_project(self, project_id: str) -> Optional[dict]: ...
    async def get_projects_for_user(self, user_id: str) -> list[dict]: ...
    async def create_project(self, data: dict) -> Optional[dict]: ...
    async def update_project(self, project_id: str, data: dict) -> Optional[dict]: ...
    async def delete_project(self, project_id: str) -> None: ...
    async def get_project_context(self, project_id: str) -> Optional[str]: ...
    async def get_project_memory(self, project_id: str) -> Optional[dict]: ...
    async def upsert_project_memory(self, project_id: str, summary_text: str) -> None: ...
    async def delete_document_records(self, source_file: str) -> None: ...

    # ── Vector Store Operations ──
    async def insert_documents(self, documents: list[dict]) -> None: ...
    async def insert_chunks(self, chunks: list[dict]) -> None: ...
    async def delete_chunks_by_source(self, source: str) -> int: ...
    async def query_similar_chunks(self, query_text: str, query_embedding: list[float], top_k: int = 10, where: Optional[dict] = None) -> list[dict]: ...
    async def get_collection_count(self) -> int: ...

    # ── Tools Operations ──
    async def query_tax_rates(self) -> str: ...

    # ── Observability / admin dashboard (Migration 003) ──
    async def log_error(self, record: dict) -> None: ...
    async def get_errors(self, limit: int = 100, offset: int = 0, severity: str = None,
                         module: str = None, error_type: str = None, since: str = None) -> list[dict]: ...
    async def get_error_facets(self) -> dict: ...
    async def get_errors_since(self, since: str) -> list[dict]: ...

    async def create_ingestion_job(self, data: dict) -> str: ...
    async def update_ingestion_job(self, job_id: str, data: dict) -> None: ...
    async def get_ingestion_jobs(self, limit: int = 50, offset: int = 0) -> list[dict]: ...

    async def get_kb_stats(self) -> dict: ...
    async def get_runs_since(self, since: str) -> list[dict]: ...
    async def get_step_latencies_since(self, since: str) -> list[dict]: ...

    # ── Chat attachments (per-conversation; NOT the knowledge base) ──
    async def create_attachment(self, data: dict) -> dict: ...
    async def get_attachments_for_session(self, session_id: str, include_text: bool = False) -> list[dict]: ...
    async def get_attachment(self, attachment_id: str) -> Optional[dict]: ...
    async def delete_attachment(self, attachment_id: str) -> None: ...
